version: "3.7"
services:
  admin-nextjs:
    build:
      context: .
    restart: always
    networks:
      - share-network
    env_file:
      - .env
    volumes:
      - ./public:/app/public
      - ./.next:/app/.next
    ports:
      - "3000:3000" # Bind container port 3000 to host port 3000
networks:
  share-network:
    external: true
