name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify package-lock.json
        run: |
          if [ ! -f "package-lock.json" ]; then
            echo "Error: package-lock.json is missing!"
            exit 1
          fi

          LOCKFILE_VERSION=$(node -pe "require('./package-lock.json').lockfileVersion")
          if [ $LOCKFILE_VERSION -lt 2 ]; then
            echo "Error: Update package-lock.json with modern npm (run 'npm install' locally)"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: |
          npm config set audit false
          npm ci --no-fund --prefer-offline
        env:
          CI: true

      - name: Build Next.js application
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /your-repo-name
          NODE_ENV: production

      - name: Export static site
        run: npm run export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
